### ISSUE TITLE
mysql/mariadb support

### ISSUE THREAD

**Issue by apcarp** [JeffersonLab/wildfly#5]
I don't see an obvious way to support mysql/mariadb databases with this image similarly to oracle.  I have a wildfly app that uses a mysql database.  I hope it is relatively straightforward to add similar functionality for mariadb/mysql as exists for oracle.

**Comment by slominskir** [comment]
Need to add a function to `server-setup.sh` to download and install the MySQL (actually prob MariaDB) driver during server setup similar to the oracle equivalent: https://github.com/JeffersonLab/wildfly/blob/029939b9da16a87cd8487952b01a7aa615cad0b1/scripts/server-setup.sh#L83

Then add a function to the `app-setup.sh` for MySQL similar to the oracle equivalent:

https://github.com/JeffersonLab/wildfly/blob/029939b9da16a87cd8487952b01a7aa615cad0b1/scripts/app-setup.sh#L91

**Aside**
I've been experimenting with the best way to manage a bash library and it may be to "import" a set of functions by sourcing instead of executing a script with env args.   This is relevant in that the current Wildfly scripts by default execute all functions in order unless you pass a command line arg.  In other words: if users must choose between MySQL or Oracle it's probably better to avoid default and instead force users to explicitly enumerate desired functions.   We may end up modifying the Wildfly scripts to work more like the new way I'm handling the Keycloak bash scripts here: https://github.com/JeffersonLab/keycloak/blob/main/scripts/lib.sh

and for example, the `lib.sh` is sourced and then functions are invoked such as:

https://github.com/JeffersonLab/keycloak/blob/main/container/keycloak/initdb.d/04_accounts.sh
